[workspace]

members = [
  "tokio",
  "tokio-macros",
  "tokio-test",
  "tokio-stream",
  "tokio-util",

  # Internal
  "benches",
  "examples",
  "stress-test",
  "tests-build",
  "tests-integration",
]

[patch.crates-io]
socket2 = { git = "https://github.com/kawadakk/socket2", branch = "feat-solid-support" }
mio = { git = "https://github.com/kawadakk/mio", branch = "feat-solid-support-v0.7.x" }
